---
all:
  children:
    app_servers:
      children:
        dev:
          hosts:
            app-dev:
              ansible_host: DEV_HOST_IP
        staging:
          hosts:
            app-staging:
              ansible_host: STAGING_HOST_IP
