apiVersion: v1
kind: ResourceQuota
metadata:
  name: devops-demo-quota
  namespace: devops-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.memory: 6Gi
    pods: "12"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: devops-demo-defaults
  namespace: devops-demo
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
